"use client";

import { useEffect, useState } from "react";
import { MapPin, ShieldCheck, Clock } from "lucide-react";

export default function SafetyCheckInPage({ params }: { params: Promise<{ token: string }> }) {
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState("");
  useEffect(() => { params.then(({ token }) => fetch(`/api/safety-checkin/${encodeURIComponent(token)}`, { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); }).catch((err) => setError(err.message || "Unable to load check-in."))); }, [params]);
  if (error) return <main className="min-h-screen flex items-center justify-center bg-slate-50 p-6"><div className="max-w-md rounded-2xl bg-white border p-8 text-center"><ShieldCheck className="mx-auto mb-4 h-12 w-12 text-slate-400" /><h1 className="text-2xl font-bold">Check-in unavailable</h1><p className="mt-3 text-slate-600">{error}</p></div></main>;
  if (!data) return <main className="min-h-screen flex items-center justify-center text-slate-600">Loading safety check-in…</main>;
  return <main className="min-h-screen bg-emerald-50 p-6"><div className="mx-auto max-w-lg rounded-3xl bg-white p-6 shadow-sm border border-emerald-100"><div className="flex items-center gap-3"><div className="rounded-2xl bg-emerald-100 p-3"><ShieldCheck className="h-7 w-7 text-emerald-700" /></div><div><p className="text-xs font-bold uppercase tracking-wide text-emerald-700">Safety check-in</p><h1 className="text-2xl font-black">{data.firstName} shared their location</h1></div></div><div className={`mt-6 rounded-2xl p-4 ${data.status === "SAFE" ? "bg-emerald-100 text-emerald-900" : "bg-amber-100 text-amber-900"}`}><p className="font-bold">{data.status === "SAFE" ? "They confirmed they are safe." : "Check-in is active."}</p><p className="mt-1 text-sm">{data.status === "SAFE" ? `Confirmed at ${new Date(data.checkedInAt).toLocaleString()}` : "They have not yet confirmed they are safe."}</p></div>{data.label && <p className="mt-5 font-semibold">{data.label}</p>}<div className="mt-5 flex items-center gap-2 text-sm text-slate-600"><Clock className="h-4 w-4" /> Expires {new Date(data.expiresAt).toLocaleString()}</div><a className="mt-6 flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 font-bold text-white" target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${data.latitude}&mlon=${data.longitude}#map=16/${data.latitude}/${data.longitude}`}><MapPin className="h-4 w-4" /> View last known location</a><p className="mt-5 text-xs text-slate-500">This link shows only the shared location and check-in status. It expires automatically.</p></div></main>;
}
