import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "../../auth/[...nextauth]/route";
import { prisma } from "../../../../lib/prisma";
import { writeAuditLog } from "../../../../lib/audit";

export async function GET(request: NextRequest) {
  const session = await getServerSession(authOptions);
  const actor = session?.user as { id?: string; role?: string } | undefined;
  if (!actor?.id || actor.role !== "ADMIN") return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const userId = new URL(request.url).searchParams.get("userId")?.trim();
  if (!userId || userId.length > 100) return NextResponse.json({ error: "A valid userId is required" }, { status: 400 });
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: {
      id: true, name: true, email: true, emailVerified: true, image: true, role: true, phone: true, whatsapp: true, state: true, batch: true,
      ppaState: true, ppaLga: true, ppaLatitude: true, ppaLongitude: true, createdAt: true,
      properties: { select: { id: true, title: true, location: true, state: true, lga: true, status: true, createdAt: true } },
      bookings: { select: { id: true, propertyId: true, date: true, time: true, status: true, createdAt: true } },
      reviews: { select: { id: true, propertyId: true, rating: true, comment: true, createdAt: true } },
      sentMessages: { select: { id: true, content: true, senderId: true, receiverId: true, createdAt: true, read: true } },
      receivedMessages: { select: { id: true, content: true, senderId: true, receiverId: true, createdAt: true, read: true } },
      safetyCheckIns: { select: { id: true, propertyId: true, label: true, expiresAt: true, status: true, createdAt: true } },
    },
  });
  if (!user) return NextResponse.json({ error: "User not found" }, { status: 404 });
  await writeAuditLog("NDPR_DATA_EXPORT", user.id, `Personal data export generated by administrator ${actor.id}`);
  return NextResponse.json({ exportedAt: new Date().toISOString(), subject: user }, { headers: { "Cache-Control": "no-store", "Content-Disposition": `attachment; filename="nysc-ndpr-export-${user.id}.json"` } });
}
