packages:
  - '.'
allowBuilds:
  '@firebase/util': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  prisma: true
  protobufjs: true
patchedDependencies:
  openid-client@5.7.1: patches/openid-client@5.7.1.patch
