"use client";

import { useMemo, useState } from "react";
import { useSession } from "next-auth/react";
import Link from "next/link";
import { ArrowLeft, Crown, Lock, Phone, MessageCircle, ShieldAlert } from "lucide-react";
import { EMERGENCY_CATEGORIES, EMERGENCY_CONTACTS } from "../../../lib/emergencyContacts";

function Gate() { return <div className="min-h-[80vh] flex items-center justify-center p-6"><div className="max-w-md text-center"><Lock className="mx-auto mb-4 h-12 w-12 text-amber-500" /><h1 className="text-2xl font-black">Emergency quick-dial</h1><p className="my-4 text-sm text-slate-600">Premium members get a curated emergency reference directory.</p><Link href="/member/premium" className="inline-flex items-center gap-2 rounded-xl bg-amber-500 px-5 py-3 font-bold"><Crown className="h-4 w-4" /> Upgrade to Premium</Link></div></div>; }
export default function EmergencyPage() { const { data: session, status } = useSession(); const user = session?.user as any; const premium = Boolean(user?.isPremium && user?.premiumPlan === "CORP_PREMIUM" && (!user?.premiumExpiry || new Date(user.premiumExpiry).getTime() > Date.now())); const [state, setState] = useState(user?.state || "National"); const contacts = useMemo(() => EMERGENCY_CONTACTS.filter((contact) => contact.state === "National" || contact.state === state), [state]); if (status === "loading") return <div className="p-8">Loading…</div>; if (!premium) return <Gate />; return <main className="min-h-screen bg-slate-50 p-5 md:p-10"><div className="mx-auto max-w-4xl"><Link href="/member" className="mb-6 inline-flex items-center gap-2 text-sm"><ArrowLeft className="h-4 w-4" /> Back</Link><div className="flex items-center gap-3"><ShieldAlert className="h-8 w-8 text-emerald-700" /><div><h1 className="text-2xl font-black">Emergency quick-dial</h1><p className="text-sm text-slate-600">Reference numbers can change; verify locally when safe.</p></div></div><select value={state} onChange={(event) => setState(event.target.value)} className="mt-6 w-full rounded-xl border bg-white p-3"><option>National</option>{[...new Set(EMERGENCY_CONTACTS.map((contact) => contact.state).filter((value) => value !== "National"))].map((value) => <option key={value}>{value}</option>)}</select><div className="mt-6 grid gap-4 md:grid-cols-2">{contacts.map((contact) => <article key={`${contact.state}-${contact.category}`} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-emerald-700">{EMERGENCY_CATEGORIES[contact.category]}</p><h2 className="mt-1 font-bold">{contact.name}</h2><p className="mt-2 text-sm text-slate-600">{contact.notes || "Confirm current availability for your area."}</p><div className="mt-4 flex gap-2"><a href={`tel:${contact.phone}`} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-emerald-700 px-3 py-2 font-bold text-white"><Phone className="h-4 w-4" /> Call</a>{contact.whatsapp && <a href={`https://wa.me/${contact.whatsapp}`} className="flex items-center justify-center gap-2 rounded-xl border px-3 py-2 font-bold"><MessageCircle className="h-4 w-4" /> WhatsApp</a>}</div></article>)}</div></div></main>; }
